### PR TITLE
New filter

### PR DESCRIPTION
**Pull request by iK4oS**
Suggested by SpinnySpiwal#0001
https://discord.com/channels/731881028573986874/996775308604747777/1006194524739080214

### CODE REVIEW

**Review by LolloDev5123 — APPROVED** [review]
I love how this repo is a troll for people who can't read lua!
You have funny little fake backdoor checks when this script itself is a backdoor! Funny

**Comment by iK4oS** [comment]
Show us, where is the backdoor at?

**Comment by DimensionalFusion** [comment]
Backdoor.

**Comment by SRK1D** [comment]
backdur

**Comment by uniquadev** [comment]
> I love how this repo is a troll for people who can't read lua!
> You have funny little fake backdoor checks when this script itself is a backdoor! Funny

Do you know what a backdoor does or even mean?

**Comment by SRK1D** [comment]
> 

its cheese

**Pull request closed without merging**
